name: Advanced ML Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install mlflow dagshub pandas scikit-learn joblib google-api-python-client google-auth docker

      - name: Run mlflow project
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USER_NAME: ${{ secrets.DAGSHUB_USERNAME }}
        run: python Membangun_model/modelling.py

      - name: Get latest MLflow run_id
        run: echo "RUN_ID=$(date +%s)" >> $GITHUB_ENV

      - name: Upload to Google Drive
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > gcp_key.json
          python scripts/upload_to_drive.py

      - name: Build and Push Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:${{ github.sha }}
