name: Advanced ML Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Check Env
        run: |
          python --version
          env

      - name: Install Python dependencies
        run: pip install mlflow docker pytest flake8 dagshub pandas scikit-learn joblib google-api-python-client google-auth

      - name: Run mlflow project
        run: python Membangun_model/modelling.py

      - name: Get latest MLflow run_id
        run: echo "RUN_ID=$(date +%s)" >> $GITHUB_ENV

      - name: Upload to Google Drive
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > gcp_key.json
          python scripts/upload_to_drive.py

      - name: Build Docker Model
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and Push Docker Image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:${{ github.sha }}
